export const sampleModelPricingData = {
  vendors: [
    {
      id: 1,
      name: 'OpenAI',
      icon: 'OpenAI',
      description: '通用文本、视觉和工具调用模型，适合多数生产场景。',
    },
    {
      id: 2,
      name: 'Anthropic',
      icon: 'Anthropic',
      description: '长文本理解、复杂推理和严肃写作场景的高质量模型。',
    },
    {
      id: 3,
      name: 'DeepSeek',
      icon: 'DeepSeek',
      description: '高性价比中文、代码和通用对话模型。',
    },
    {
      id: 4,
      name: 'Stability AI',
      icon: 'Stability',
      description: '图像生成和创意生产模型。',
    },
    {
      id: 5,
      name: 'Google',
      icon: 'Google',
      description: '长上下文、多模态理解和视频生成能力的模型供应商。',
    },
    {
      id: 6,
      name: 'Alibaba Cloud',
      icon: 'Qwen',
      description: '适合中文、代码、Agent 和多模态场景的通义千问模型。',
    },
    {
      id: 7,
      name: 'ElevenLabs',
      icon: 'ElevenLabs',
      description: '语音合成与音频生成服务，适合播客、客服和内容制作。',
    },
  ],
  group_ratio: {
    batch: 0.6,
    default: 1,
    vip: 1.35,
    enterprise: 1.8,
  },
  usable_group: {
    batch: '低成本批处理分组，适合报表生成、批量摘要等不要求实时返回的任务。',
    default: '标准分组，适合日常对话、文本生成和常规业务调用。',
    vip: '优先分组，提供更高的可用性和响应优先级，适合线上核心链路。',
    enterprise:
      '价格换算后约为官方 4.5 折，适合 Claude Code 场景下对稳定性、渠道来源、模型一致性和业务连续性要求较高的场景。我们采用复合渠道负载均衡来降低单点故障率，渠道优先采用 Anthropic 官方 API、AWS Bedrock、Google Vertex AI 等经官方支持的高质渠道。进入该分组的供应链路需通过多项模型真实性验真，包括身份一致性、协议/指纹特征、指令遵循、数学题、逻辑题、官方正样本对照等适用测试；运行侧需满足成功率、P95 时延、缓存命中、缓存成本核验及适用能力质检等检查项。',
  },
  supported_endpoint: {
    chat: {
      path: '/v1/chat/completions',
      method: 'POST',
    },
    responses: {
      path: '/v1/responses',
      method: 'POST',
    },
    embeddings: {
      path: '/v1/embeddings',
      method: 'POST',
    },
    images: {
      path: '/v1/images/generations',
      method: 'POST',
    },
    audio: {
      path: '/v1/audio/transcriptions',
      method: 'POST',
    },
    speech: {
      path: '/v1/audio/speech',
      method: 'POST',
    },
    video: {
      path: '/v1/videos/generations',
      method: 'POST',
    },
    rerank: {
      path: '/v1/rerank',
      method: 'POST',
    },
  },
  data: [
    {
      model_name: 'gpt-4o-mini',
      description:
        '轻量、低延迟的多模态模型，适合客服助手、内容改写和工具调用。',
      tags: 'fast,vision,function-calling',
      quota_type: 0,
      model_ratio: 0.075,
      completion_ratio: 4,
      cache_ratio: 0.25,
      create_cache_ratio: 1.25,
      image_ratio: 1.5,
      enable_groups: ['batch', 'default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'gpt-4o',
      description: '高质量通用旗舰模型，适合复杂对话、视觉理解和业务自动化。',
      tags: 'flagship,vision,function-calling',
      quota_type: 0,
      model_ratio: 1.25,
      completion_ratio: 4,
      cache_ratio: 0.5,
      create_cache_ratio: 1.25,
      image_ratio: 2,
      enable_groups: ['default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'claude-3-5-sonnet',
      description: '擅长长文本、代码审阅和复杂指令跟随，适合高质量分析任务。',
      tags: 'reasoning,long-context,coding',
      quota_type: 0,
      model_ratio: 1.5,
      completion_ratio: 5,
      cache_ratio: 0.1,
      create_cache_ratio: 1.25,
      enable_groups: ['vip', 'enterprise'],
      supported_endpoint_types: ['chat'],
      vendor_id: 2,
    },
    {
      model_name: 'deepseek-v4-flash',
      description: '高性价比中文对话和代码模型，适合大批量文本处理。',
      tags: 'cost-effective,chat,coding',
      quota_type: 0,
      model_ratio: 0.07,
      completion_ratio: 4,
      cache_ratio: 0.25,
      enable_groups: ['batch', 'default'],
      supported_endpoint_types: ['chat'],
      vendor_id: 3,
    },
    {
      model_name: 'stable-image-ultra',
      description: '高质量图片生成模型，按次计费，适合商品图、海报和创意素材。',
      tags: 'image,generation,creative',
      quota_type: 1,
      model_price: 0.04,
      enable_groups: ['default', 'vip'],
      supported_endpoint_types: ['images'],
      vendor_id: 4,
    },
    {
      model_name: 'gemini-2.5-pro',
      description:
        '长上下文多模态旗舰模型，适合复杂推理、文档理解、视觉问答和跨文件分析。',
      tags: 'flagship,vision,long-context,reasoning',
      quota_type: 0,
      model_ratio: 1.25,
      completion_ratio: 8,
      cache_ratio: 0.25,
      image_ratio: 1.5,
      enable_groups: ['default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 5,
    },
    {
      model_name: 'qwen3-coder-plus',
      description:
        '面向代码生成、仓库理解和 Agent 工作流的中文友好模型，展示有缓存创建价格的样例。',
      tags: 'coding,agent,function-calling,reasoning',
      quota_type: 0,
      model_ratio: 0.4,
      completion_ratio: 5,
      cache_ratio: 0.2,
      create_cache_ratio: 1.1,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 6,
    },
    {
      model_name: 'text-embedding-3-large',
      description:
        '高精度文本向量模型，适合知识库检索、语义召回和相似度计算；没有输出、缓存读取和缓存创建价格时会显示 -。',
      tags: 'embedding,vector,retrieval',
      quota_type: 0,
      model_ratio: 0.13,
      enable_groups: ['default', 'vip'],
      supported_endpoint_types: ['embeddings'],
      vendor_id: 1,
    },
    {
      model_name: 'qwen-omni-audio',
      description: '多模态音频理解模型，适合语音转写、会议纪要和音频问答场景。',
      tags: 'audio,multimodal,speech',
      quota_type: 0,
      model_ratio: 0.3,
      completion_ratio: 2,
      audio_ratio: 1.5,
      audio_completion_ratio: 2,
      enable_groups: ['default', 'vip'],
      supported_endpoint_types: ['chat', 'audio', 'speech'],
      vendor_id: 6,
    },
    {
      model_name: 'eleven-multilingual-v2',
      description:
        '多语言语音合成模型，按次计费，适合播客配音、语音客服和内容生产。',
      tags: 'speech,audio,tts',
      quota_type: 1,
      model_price: 0.018,
      enable_groups: ['default', 'vip', 'enterprise'],
      supported_endpoint_types: ['speech'],
      vendor_id: 7,
    },
    {
      model_name: 'veo-3-fast',
      description:
        '快速视频生成模型，按次计费，适合短视频分镜、广告草图和创意验证。',
      tags: 'video,generation,creative',
      quota_type: 1,
      model_price: 0.5,
      enable_groups: ['vip', 'enterprise'],
      supported_endpoint_types: ['video'],
      vendor_id: 5,
    },
    {
      model_name: 'gpt-5',
      description:
        'OpenAI 旗舰通用模型，适合复杂推理、代码生成、多工具调用和长流程自动化。',
      tags: 'flagship,reasoning,coding,function-calling',
      quota_type: 0,
      model_ratio: 0.625,
      completion_ratio: 8,
      cache_ratio: 0.1,
      create_cache_ratio: 1.25,
      enable_groups: ['default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'gpt-5-mini',
      description:
        '轻量推理模型，兼顾速度和复杂任务处理能力，适合高频业务请求和 Agent 场景。',
      tags: 'fast,reasoning,agent,function-calling',
      quota_type: 0,
      model_ratio: 0.125,
      completion_ratio: 8,
      cache_ratio: 0.1,
      create_cache_ratio: 1.25,
      enable_groups: ['batch', 'default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'gpt-4.1',
      description:
        '面向生产级代码、长上下文理解和工具调用的通用模型，适合稳定业务工作流。',
      tags: 'coding,long-context,function-calling',
      quota_type: 0,
      model_ratio: 1,
      completion_ratio: 4,
      cache_ratio: 0.25,
      create_cache_ratio: 1.25,
      enable_groups: ['default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'gpt-4.1-mini',
      description:
        '成本更低的 4.1 系列模型，适合分类、抽取、轻量代码处理和批量文本任务。',
      tags: 'fast,coding,batch,function-calling',
      quota_type: 0,
      model_ratio: 0.2,
      completion_ratio: 4,
      cache_ratio: 0.25,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'gpt-4.1-nano',
      description:
        '4.1 系列的低成本小模型，适合高频分类、摘要、抽取和轻量工具调用场景。',
      tags: 'fast,cost-effective,batch,function-calling',
      quota_type: 0,
      model_ratio: 0.05,
      completion_ratio: 4,
      cache_ratio: 0.25,
      create_cache_ratio: 1.25,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 1,
    },
    {
      model_name: 'claude-sonnet-4-20250514',
      description:
        'Claude Sonnet 4 系列模型，适合代码理解、复杂指令遵循、长文档分析和高稳定性对话。',
      tags: 'coding,reasoning,long-context,agent',
      quota_type: 0,
      model_ratio: 1.5,
      completion_ratio: 5,
      cache_ratio: 0.1,
      create_cache_ratio: 1.25,
      enable_groups: ['vip', 'enterprise'],
      supported_endpoint_types: ['chat'],
      vendor_id: 2,
    },
    {
      model_name: 'claude-opus-4-1-20250805',
      description:
        'Claude Opus 4.1 系列模型，适合高难度代码任务、深度推理和对一致性要求高的业务流程。',
      tags: 'flagship,coding,reasoning,long-context',
      quota_type: 0,
      model_ratio: 7.5,
      completion_ratio: 5,
      cache_ratio: 0.1,
      create_cache_ratio: 1.25,
      enable_groups: ['enterprise'],
      supported_endpoint_types: ['chat'],
      vendor_id: 2,
    },
    {
      model_name: 'claude-3-5-haiku-20241022',
      description:
        'Claude 轻量低延迟模型，适合快速问答、客服、结构化抽取和高并发自动化任务。',
      tags: 'fast,chat,extraction',
      quota_type: 0,
      model_ratio: 0.4,
      completion_ratio: 5,
      cache_ratio: 0.1,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat'],
      vendor_id: 2,
    },
    {
      model_name: 'deepseek-v4-pro',
      description:
        'DeepSeek 推理模型，适合数学、逻辑、代码推导和需要显式思考链路的复杂任务。',
      tags: 'reasoning,coding,math',
      quota_type: 0,
      model_ratio: 0.275,
      completion_ratio: 4,
      cache_ratio: 0.25,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat'],
      vendor_id: 3,
    },
    {
      model_name: 'gemini-2.5-flash',
      description:
        '低延迟多模态模型，适合实时问答、视觉理解、工具调用和批量内容处理。',
      tags: 'fast,vision,multimodal,function-calling',
      quota_type: 0,
      model_ratio: 0.15,
      completion_ratio: 8.333,
      cache_ratio: 0.25,
      enable_groups: ['batch', 'default', 'vip', 'enterprise'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 5,
    },
    {
      model_name: 'gemini-2.5-flash-lite',
      description:
        '更轻量的 Gemini Flash 模型，适合摘要、分类、低成本文本生成和简单多模态任务。',
      tags: 'fast,cost-effective,vision',
      quota_type: 0,
      model_ratio: 0.05,
      completion_ratio: 4,
      enable_groups: ['batch', 'default'],
      supported_endpoint_types: ['chat', 'responses'],
      vendor_id: 5,
    },
    {
      model_name: 'qwen-plus',
      description:
        '通义千问均衡模型，适合中文写作、知识问答、工具调用和日常业务自动化。',
      tags: 'chat,chinese,function-calling',
      quota_type: 0,
      model_ratio: 0.12,
      completion_ratio: 3,
      cache_ratio: 0.2,
      enable_groups: ['batch', 'default', 'vip'],
      supported_endpoint_types: ['chat'],
      vendor_id: 6,
    },
    {
      model_name: 'qwen-turbo',
      description:
        '通义千问高速模型，适合高并发对话、内容改写、意图识别和轻量结构化输出。',
      tags: 'fast,chat,chinese,cost-effective',
      quota_type: 0,
      model_ratio: 0.04,
      completion_ratio: 3,
      enable_groups: ['batch', 'default'],
      supported_endpoint_types: ['chat'],
      vendor_id: 6,
    },
  ],
};
